### PR TITLE
fix: propagating lifecycle events to AndroidScreenLifecycleOwner

### LINKED ISSUE #173: Add onCreate and onDestroy in Lifecycle?
Add onCreate and onDestroy in Lifecycle? I wanna cancel my scope in VM when I exactly will know that Screen is destroyed and don't used

### LINKED ISSUE #186: Add Android lifecycle callbacks into AndroidScreenLifecycleOwner
Extend registerLifecycleListener fun of AndroidScreenLifecycleOwner with onPause and other lifecycle callbacks (and call internal onStop() from existing onStop-callback) to manage lifecycle on Android-side (e.g. collectAsStateWithLifecycle).

### LINKED ISSUE #225: `Screen`s are not paused when app is in the background or when in another Activity
In `1.0.0-rc07`, the `Screen`s seem to not pause, for example when we put the app in the background, or when we are in another `Activity`. 

Each `Screen` will only pause when we move to another screen.

With this sample code:

```kotlin
class MainActivity : ComponentActivity() {
    private val count by lazy { intent?.getIntExtra(COUNT, 0) ?: 0 }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            VoyagerDemoTheme {
                Navigator(Screen1(count))
            }
        }
    }

    companion object {
        private const val COUNT = "COUNT"
        fun getIntent(context: Context, count: Int): Intent =
            Intent(context, MainActivity::class.java).apply { putExtra(COUNT, count) }
    }
}

class Screen1(private val count: Int) : Screen {
    override val key: ScreenKey = uniqueScreenKey

    @Composable
    override fun Content() {
        val lifecycleOwner = LocalLifecycleOwner.current
        val context = LocalContext.current
        val navigator = LocalNavigator.currentOrThrow
        LaunchedEffect(key1 = Unit) {
            Log.d("Screen", "$count started LaunchedEffect from ${context.hashCode()}")
            lifecycleOwner.repeatOnLifecycle(Lifecycle.State.RESUMED) {
                while (true) {
                    delay(500)
                    Log.d("Screen", "$count is resumed from ${context.hashCode()}")
                }
            }
        }
        Column {
            Text(text = "I am $count")
            Button(
                onClick = { context.startActivity(MainActivity.getIntent(context, count + 1)) }
            ) {
                Text(text = "Start new Activity")
            }
            Button(
                onClick = { navigator.push(Screen1(count + 1)) }
            ) {
                Text(text = "Push new Screen")
            }
        }
    }
}
```

And the dependencies:
```kts
val voyagerVersion = "1.0.0-rc07"
implementation("cafe.adriel.voyager:voyager-navigator:$voyagerVersion")
```

When we:
1. Put app in the background
2. Logs are still being printed -> it means the Composable is still `RESUMED` when app is in the background
3. Does not work as expected :x: 

When we:
1. Create a new Activity
2. Logs from the first Activity are still being printed -> it means the Composable from the first Activity is still `RESUMED` when its Activity is actually paused
3. Does not work as expected :x: 

When we:
1. Push a new Screen
2. Logs from the first screen are no longer printed - the LaunchedEffect was cancelled
3. Go back
4. LaunchedEffect is started again because we see the log `0 started LaunchedEffect`.
5. Works as expected ✅ 

If we rollback to `1.0.0-rc05`, with the same sample code, the Screen is paused when we put the app in the background, or when we move to another Activity. The `LaunchedEffect` themselves are not cancelled, but the `repeatOnLifecycle` works as expected (they restart when we enter the `Screen` that is being shown to the user)

### PR DESCRIPTION
**Pull request by DevSrSouza**
fixes #225
fixes #186
fixes #173

### CODE REVIEW

File: voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt [hunk 1]
```diff
@@ -153,20 +156,52 @@ public class AndroidScreenLifecycleOwner private constructor() :
...
 
-    private fun registerLifecycleListener(outState: Bundle) {
-        val activity = atomicContext.get()?.getActivity()
-        if (activity != null && activity is LifecycleOwner) {
+    private fun registerLifecycleListenerForSaveState(outState: Bundle) {
+        val lifecycleOwner = getParentLifecycleOwnerOrActivityOrNull()
+        if (lifecycleOwner != null) {
             val observer = object : DefaultLifecycleObserver {
                 override fun onStop(owner: LifecycleOwner) {
                     performSave(outState)
```
Comment (Syer10) [inline voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt:164]: This can be moved to the proper lifecycle listener

File: voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt [hunk 2]
```diff
@@ -153,20 +156,52 @@ public class AndroidScreenLifecycleOwner private constructor() :
...
             lifecycle.addObserver(observer)
             deactivateLifecycleListener = { lifecycle.removeObserver(observer) }
         }
     }
 
+    /**
+     * Returns a unregister callback
+     */
+    private fun registerLifecycleListenerPropagation(): () -> Unit {
+        val lifecycleOwner = getParentLifecycleOwnerOrActivityOrNull()
```
Comment (Syer10) [inline voyager-core/src/androidMain/kotlin/cafe/adriel/voyager/androidx/AndroidScreenLifecycleOwner.kt:177]: Why are we doing this instead of just using atomicParentLifecycleOwner?

**Comment by DevSrSouza** [comment]
Did some cleanup and some documentation @Syer10

**Review by Syer10 — APPROVED** [review]
